function(setup_default_lv2_path)
    if (MSVC OR WIN32)
        set(DEFAULT_LV2_FOLDER "${CMAKE_INSTALL_PREFIX}/lv2" PARENT_SCOPE)
    elseif(APPLE)
        set(DEFAULT_LV2_FOLDER "$ENV{HOME}/Library/Audio/Plug-ins/lv2" PARENT_SCOPE)
    elseif(UNIX OR ANDROID_PLATFORM)
        set(DEFAULT_LV2_FOLDER "$ENV{HOME}/.lv2" PARENT_SCOPE)
    endif()
endfunction()
