name: cmake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:  |
        if [ "$RUNNER_OS" == "Linux" ]; then
              apt install important_linux_software
        elif [ "$RUNNER_OS" == "Windows" ]; then
              dir
        else
              echo "$RUNNER_OS not supported"
              exit 1
        fi
    - name: initialize
      run: git submodule update --init
    - name: configure
      run: cmake .
    - name: build
      run: cmake --build .
    - name: install
      run: cmake --build . --target install
    - uses: actions/upload-artifact@v1
      with:
        name: abNinjam
        path: /home/runner/.vst3/
