name: cmake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run:  |
        if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libxcb-util-dev libxcb-cursor-dev libxcb-keysyms1-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libvorbis-dev
        elif [ "$RUNNER_OS" == "Windows" ]; then
              git clone https://github.com/xiph/ogg.git
              cd ogg
              cmake .
              cmake --build .
              cmake --build . --target install
              cd ..
              git clone https://github.com/xiph/vorbis.git
              cd vorbis
              cmake -DOGG_INCLUDE_DIR="C:/Program Files (x86)/libogg/include/" -DOGG_LIBRARY="C:/Program Files (x86)/libogg/lib/" .
              cmake --build .
              cmake --build . --target install
        else
              echo "$RUNNER_OS not supported"
              exit 1
        fi
    - name: initialize
      run: git submodule update --init
    - name: configure
      run:  |
        if [ "$RUNNER_OS" == "Linux" ]; then
              cmake .
        elif [ "$RUNNER_OS" == "Windows" ]; then
              cmake -DVORBISENC_INCLUDE_DIR="C:/Program Files (x86)/vorbis/include/" -DVORBISENC_LIBRARY="C:/Program Files (x86)/vorbis/lib/vorbisenc.lib" .
        else
              echo "$RUNNER_OS not supported"
              exit 1
        fi
    - name: build
      run: cmake --build .
    - name: install
      run: cmake --build . --target install
    - uses: actions/upload-artifact@v1
      with:
        name: abNinjam
        path: /home/runner/.vst3/
